  - name: To install Pymysql
    ansible.builtin.pip:
     name: 
     - PyMySQL
     executable: pip3.9

  - name: To install sql server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: To start sql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes

  - name: To connect to sql server
    community.mysql.mysql_info:
     login_user: "root"
     login_passord: "{{ password }}"
     login_host: "{{ host_address }}"
    ignore_errors: yes
    register: mysql_info

  - name: To print the sql info
    ansible.builtin.debug:
     msg: "{{ mysql_info }}"

  - name: To change the root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ password }}"
    when: mysql_info.failed is true
